// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  mcserver.js  —  Minecraft Server Library for ZPP                           ║
// ║  Import as: mcserver.zl                                                     ║
// ║  All functions are injected globally with the __ prefix.                    ║
// ║                                                                              ║
// ║  CAPABILITIES:                                                               ║
// ║   • Vanilla, Fabric, NeoForge, Paper, Purpur server creation                ║
// ║   • Auto-download of any MC version (latest → legacy)                       ║
// ║   • Full mod & plugin management (local + Modrinth)                         ║
// ║   • Player management, commands, events                                      ║
// ║   • World backup / restore                                                   ║
// ║   • RCON client                                                              ║
// ║   • Remote server ping (status protocol)                                    ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

'use strict';

// ── Node built-ins ─────────────────────────────────────────────────────────────
const childProcess = require('child_process');
const fs           = require('fs');
const path         = require('path');
const https        = require('https');
const http         = require('http');
const net          = require('net');
const os           = require('os');
const readline     = require('readline');
const { EventEmitter } = require('events');

// ── Internal state ─────────────────────────────────────────────────────────────
const _MC_SERVERS  = new Map();   // serverId  -> ServerInstance
const _MC_RCONS    = new Map();   // rconId    -> RconConnection
let   _srvCounter  = 0;
let   _rconCounter = 0;

// ── Remote endpoints ───────────────────────────────────────────────────────────
const MOJANG_MANIFEST = 'https://launchermeta.mojang.com/mc/game/version_manifest_v2.json';
const FABRIC_META     = 'https://meta.fabricmc.net';
const NEOFORGE_MAVEN  = 'https://maven.neoforged.net';
const PAPER_API       = 'https://api.papermc.io/v2';
const PURPUR_API      = 'https://api.purpurmc.org/v2';
const MODRINTH_API    = 'https://api.modrinth.com/v2';

// ══════════════════════════════════════════════════════════════════════════════
//  PRIVATE HELPERS
// ══════════════════════════════════════════════════════════════════════════════

/** HTTP/HTTPS GET → resolves to response body string.  Follows redirects. */
function _fetch(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith('https') ? https : http;
    mod.get(url, { headers: { 'User-Agent': 'ZPP-MCServer/1.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return _fetch(res.headers.location).then(resolve).catch(reject);
      }
      let raw = '';
      res.on('data', c => raw += c);
      res.on('end',  () => resolve(raw));
    }).on('error', reject);
  });
}

/** Download a remote URL to a local file path.  Follows redirects. */
function _download(url, dest) {
  return new Promise((resolve, reject) => {
    const mod  = url.startsWith('https') ? https : http;
    const file = fs.createWriteStream(dest);
    mod.get(url, { headers: { 'User-Agent': 'ZPP-MCServer/1.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        file.close();
        try { fs.unlinkSync(dest); } catch (_) {}
        return _download(res.headers.location, dest).then(resolve).catch(reject);
      }
      res.pipe(file);
      file.on('finish', () => file.close(resolve));
      file.on('error',  reject);
    }).on('error', (e) => { try { fs.unlinkSync(dest); } catch (_) {} reject(e); });
  });
}

/** Parse a server.properties file into a plain object. */
function _readProps(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return fs.readFileSync(filePath, 'utf8')
    .split('\n')
    .filter(l => l.includes('=') && !l.trimStart().startsWith('#'))
    .reduce((acc, l) => {
      const eq = l.indexOf('=');
      acc[l.slice(0, eq).trim()] = l.slice(eq + 1).trim();
      return acc;
    }, {});
}

/** Write a plain object back to a server.properties file. */
function _writeProps(filePath, props) {
  const lines = [
    '#Minecraft server properties',
    `#Generated by ZPP mcserver.zl  ${new Date().toISOString()}`,
    ...Object.entries(props).map(([k, v]) => `${k}=${v}`),
  ];
  fs.writeFileSync(filePath, lines.join('\n') + '\n');
}

/** Check whether the system Java meets a minimum major version. */
function _javaCheck(min = 17) {
  try {
    const out   = childProcess.execSync('java -version 2>&1', { encoding: 'utf8' });
    const match = out.match(/version "(\d+)/);
    const ver   = match ? parseInt(match[1]) : 0;
    return { available: true, version: ver, meets: ver >= min };
  } catch {
    return { available: false, version: 0, meets: false };
  }
}

/** Get the Mojang version manifest (cached per process run). */
let _manifestCache = null;
async function _manifest() {
  if (!_manifestCache) {
    _manifestCache = JSON.parse(await _fetch(MOJANG_MANIFEST));
  }
  return _manifestCache;
}

/** Resolve 'latest' / 'latest_snapshot' / a real version ID. */
async function _resolveVersion(requested) {
  const m = await _manifest();
  if (!requested || requested === 'latest')          return m.latest.release;
  if (requested === 'latest_snapshot')               return m.latest.snapshot;
  const found = m.versions.find(v => v.id === requested);
  if (!found) throw new Error(`Minecraft version "${requested}" not found`);
  return found.id;
}

// ══════════════════════════════════════════════════════════════════════════════
//  ServerInstance  (internal class, not exported)
// ══════════════════════════════════════════════════════════════════════════════
class ServerInstance extends EventEmitter {
  constructor(id, dir, opts) {
    super();
    this.id      = id;
    this.dir     = dir;
    this.opts    = opts;
    this.process = null;
    this.running = false;
    this.players = new Set();
    this.log     = [];          // circular buffer, max 2 000 lines
    this.type    = opts.type    || 'vanilla';
    this.version = opts.version || 'latest';
    this.jarFile = opts.jarFile || 'server.jar';
  }

  /** Start the Minecraft server process. */
  start(extraJvmArgs = []) {
    if (this.running) throw new Error(`[mcserver] Server ${this.id} is already running.`);
    const jar = path.join(this.dir, this.jarFile);
    if (!fs.existsSync(jar))
      throw new Error(`[mcserver] JAR not found at ${jar} — did you call __download_server_jar first?`);

    // Auto-accept EULA
    fs.writeFileSync(path.join(this.dir, 'eula.txt'), 'eula=true\n');

    const maxRam = this.opts.ram    || '2G';
    const minRam = this.opts.minRam || '512M';
    const jvmArgs = [
      `-Xms${minRam}`, `-Xmx${maxRam}`,
      // G1GC tuning — helps with big modpacks
      '-XX:+UseG1GC',
      '-XX:+ParallelRefProcEnabled',
      '-XX:MaxGCPauseMillis=200',
      '-XX:+UnlockExperimentalVMOptions',
      '-XX:+DisableExplicitGC',
      '-XX:+AlwaysPreTouch',
      '-XX:G1NewSizePercent=30',
      '-XX:G1MaxNewSizePercent=40',
      '-XX:G1HeapRegionSize=8M',
      '-XX:G1ReservePercent=20',
      '-XX:G1HeapWastePercent=5',
      '-XX:G1MixedGCCountTarget=4',
      '-XX:InitiatingHeapOccupancyPercent=15',
      '-XX:G1MixedGCLiveThresholdPercent=90',
      '-XX:G1RSetUpdatingPauseTimePercent=5',
      '-XX:SurvivorRatio=32',
      '-XX:+PerfDisableSharedMem',
      '-XX:MaxTenuringThreshold=1',
      '-Dusing.aikars.flags=https://mcflags.emc.gs',
      ...extraJvmArgs,
      '-jar', jar, '--nogui',
    ];

    this.process = childProcess.spawn('java', jvmArgs, {
      cwd:   this.dir,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    this.running = true;

    // Attach readline to both stdout and stderr
    const attachReader = (stream) => {
      readline.createInterface({ input: stream, crlfDelay: Infinity })
        .on('line', (line) => {
          // Store line
          this.log.push({ time: Date.now(), line });
          if (this.log.length > 2000) this.log.shift();
          this.emit('log', line);

          // ── Parse key events ──────────────────────────────
          // Player join
          const joinMatch = line.match(/\[.+?\] \[.+?\/INFO\]: (.+) joined the game/);
          if (joinMatch) {
            this.players.add(joinMatch[1]);
            this.emit('player_join', joinMatch[1]);
          }
          // Player leave
          const leaveMatch = line.match(/\[.+?\] \[.+?\/INFO\]: (.+) left the game/);
          if (leaveMatch) {
            this.players.delete(leaveMatch[1]);
            this.emit('player_leave', leaveMatch[1]);
          }
          // Chat
          const chatMatch = line.match(/\[.+?\/INFO\]: <(\w+)>\s(.+)/);
          if (chatMatch) this.emit('chat', { player: chatMatch[1], message: chatMatch[2] });
          // Server ready
          if (line.includes('Done (') && line.includes('For help, type "help"'))
            this.emit('ready');
          // Crash / error
          if (line.includes('FAILED TO BIND TO PORT'))
            this.emit('error', new Error('Port already in use'));
        });
    };

    attachReader(this.process.stdout);
    attachReader(this.process.stderr);

    this.process.on('close', (code) => {
      this.running = false;
      this.players.clear();
      this.emit('stop', code);
    });
  }

  /** Write a command to the server stdin. */
  command(cmd) {
    if (!this.running || !this.process)
      throw new Error(`[mcserver] Server ${this.id} is not running.`);
    this.process.stdin.write(cmd.trim() + '\n');
  }

  /** Stop the server (graceful or force). */
  stop(force = false) {
    if (!this.running || !this.process) return;
    if (force) this.process.kill('SIGKILL');
    else       this.process.stdin.write('stop\n');
  }
}

// ══════════════════════════════════════════════════════════════════════════════
//  RconConnection  (internal class, not exported)
// ══════════════════════════════════════════════════════════════════════════════
class RconConnection {
  constructor(host, port, password) {
    this.host          = host;
    this.port          = port;
    this.password      = password;
    this.socket        = null;
    this.connected     = false;
    this.authenticated = false;
    this._id           = 0;
    this._pending      = new Map();
    this._buf          = Buffer.alloc(0);
  }

  connect() {
    return new Promise((resolve, reject) => {
      this.socket = net.createConnection({ host: this.host, port: this.port });
      this.socket.on('connect', async () => {
        this.connected = true;
        try {
          await this._write(3, this.password); // SERVERDATA_AUTH
          this.authenticated = true;
          resolve();
        } catch (e) { reject(e); }
      });
      this.socket.on('data', (chunk) => {
        this._buf = Buffer.concat([this._buf, chunk]);
        this._drain();
      });
      this.socket.on('error',  reject);
      this.socket.on('close', () => { this.connected = false; });
      this.socket.setTimeout(5000, () => reject(new Error('RCON timeout')));
    });
  }

  _drain() {
    while (this._buf.length >= 14) {
      const size = this._buf.readInt32LE(0);
      if (this._buf.length < size + 4) break;
      const id   = this._buf.readInt32LE(4);
      // const type = this._buf.readInt32LE(8);  // not needed
      const body = this._buf.slice(12, 4 + size - 2).toString('utf8');
      this._buf  = this._buf.slice(4 + size);
      const cb   = this._pending.get(id);
      if (cb) { this._pending.delete(id); cb(null, body); }
    }
  }

  _write(type, body) {
    return new Promise((resolve, reject) => {
      const id    = ++this._id;
      const bBody = Buffer.from(body, 'utf8');
      const pkt   = Buffer.alloc(14 + bBody.length);
      pkt.writeInt32LE(10 + bBody.length, 0); // size field
      pkt.writeInt32LE(id,   4);
      pkt.writeInt32LE(type, 8);
      bBody.copy(pkt, 12);
      pkt.writeInt16LE(0, 12 + bBody.length); // null terminators
      this._pending.set(id, (err, res) => err ? reject(err) : resolve(res));
      this.socket.write(pkt);
    });
  }

  command(cmd) {
    if (!this.connected || !this.authenticated)
      throw new Error('[mcserver] RCON is not connected / authenticated.');
    return this._write(2, cmd); // SERVERDATA_EXECCOMMAND
  }

  disconnect() {
    if (this.socket) this.socket.destroy();
    this.connected = false;
  }
}

// ══════════════════════════════════════════════════════════════════════════════
//  ██████████  PUBLIC API  (__  prefix)  ██████████
// ══════════════════════════════════════════════════════════════════════════════

// ─────────────────────────────────────────────────────────────────────────────
//  SERVER CREATION & LIFECYCLE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Create a new managed Minecraft server instance.
 *
 * opts {object}
 *   .dir          {string}  Absolute path for this server's folder  (auto-generated if omitted)
 *   .type         {string}  'vanilla' | 'fabric' | 'neoforge' | 'paper' | 'purpur'   (default: 'vanilla')
 *   .version      {string}  MC version e.g. '1.21.4' | 'latest'                      (default: 'latest')
 *   .ram          {string}  Max JVM heap  e.g. '4G'                                   (default: '2G')
 *   .minRam       {string}  Min JVM heap  e.g. '512M'                                 (default: '512M')
 *   .port         {number}  Server port                                                (default: 25565)
 *   .motd         {string}  Message of the day
 *   .maxPlayers   {number}  Max players                                                (default: 20)
 *   .onlineMode   {boolean} true = premium only, false = cracked                      (default: true)
 *   .gamemode     {string}  'survival' | 'creative' | 'adventure' | 'spectator'
 *   .difficulty   {string}  'peaceful' | 'easy' | 'normal' | 'hard'
 *   .pvp          {boolean}
 *   .whitelist    {boolean}
 *   .seed         {string}
 *   .viewDistance {number}
 *   .commandBlocks {boolean}
 *   .rcon         {boolean} Enable RCON
 *   .rconPort     {number}
 *   .rconPassword {string}
 *   .levelType    {string}  e.g. 'minecraft:normal' | 'minecraft:flat'
 *   .worldName    {string}  World folder name
 *   .resourcePack {string}  URL to resource pack
 *   .name         {string}  Human-readable server name
 *
 * @returns {string}  serverId  (e.g. 'mc_1')
 */
async function __create_server(opts = {}) {
  const id  = `mc_${++_srvCounter}`;
  const dir = opts.dir || path.join(process.cwd(), 'mc_servers', id);

  // Create directory structure
  for (const sub of ['', 'mods', 'plugins', 'backups', 'config', 'datapacks']) {
    fs.mkdirSync(path.join(dir, sub), { recursive: true });
  }

  // Write default server.properties
  _writeProps(path.join(dir, 'server.properties'), {
    'server-port':               opts.port            ?? 25565,
    'motd':                      opts.motd            ?? 'A ZPP Minecraft Server',
    'max-players':               opts.maxPlayers      ?? 20,
    'online-mode':               opts.onlineMode      ?? true,
    'gamemode':                  opts.gamemode        ?? 'survival',
    'difficulty':                opts.difficulty      ?? 'normal',
    'pvp':                       opts.pvp             ?? true,
    'white-list':                opts.whitelist       ?? false,
    'enforce-whitelist':         opts.whitelist       ?? false,
    'level-name':                opts.worldName       ?? 'world',
    'level-seed':                opts.seed            ?? '',
    'level-type':                opts.levelType       ?? 'minecraft\\:normal',
    'view-distance':             opts.viewDistance    ?? 10,
    'simulation-distance':       opts.simDistance     ?? 10,
    'spawn-protection':          opts.spawnProtection ?? 16,
    'enable-command-block':      opts.commandBlocks   ?? false,
    'max-world-size':            opts.maxWorldSize    ?? 29999984,
    'allow-nether':              opts.nether          ?? true,
    'allow-flight':              opts.allowFlight     ?? false,
    'enable-rcon':               opts.rcon            ?? false,
    'rcon.port':                 opts.rconPort        ?? 25575,
    'rcon.password':             opts.rconPassword    ?? '',
    'broadcast-rcon-to-ops':     true,
    'resource-pack':             opts.resourcePack    ?? '',
    'resource-pack-sha1':        opts.resourcePackSha1 ?? '',
    'resource-pack-required':    opts.resourcePackRequired ?? false,
    'op-permission-level':       4,
    'function-permission-level': 2,
    'sync-chunk-writes':         true,
    'server-name':               opts.name           ?? 'ZPP Server',
  });

  const inst = new ServerInstance(id, dir, {
    ...opts,
    type:    opts.type    || 'vanilla',
    version: opts.version || 'latest',
    ram:     opts.ram     || '2G',
    minRam:  opts.minRam  || '512M',
  });
  _MC_SERVERS.set(id, inst);
  return id;
}

/**
 * Download the official Minecraft server JAR (vanilla) for the given server.
 * Call this after __create_server before __start_server for vanilla servers.
 *
 * @param {string} serverId
 * @param {string} [version]  '1.21.4' | 'latest' | 'latest_snapshot'  (default: server's version)
 * @returns {string}  path to downloaded JAR
 */
async function __download_server_jar(serverId, version) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const v    = await _resolveVersion(version || inst.version);
  const mf   = await _manifest();
  const info = mf.versions.find(x => x.id === v);
  if (!info) throw new Error(`[mcserver] Version ${v} not in manifest`);

  const vData   = JSON.parse(await _fetch(info.url));
  const jarUrl  = vData.downloads.server.url;
  const dest    = path.join(inst.dir, 'server.jar');

  await _download(jarUrl, dest);
  inst.version = v;
  inst.jarFile = 'server.jar';
  return dest;
}

/**
 * Start the server.  The JAR must already be present (download or install first).
 *
 * @param {string}   serverId
 * @param {string[]} [extraJvmArgs]  Additional JVM flags
 * @returns {Promise<boolean>}
 */
async function __start_server(serverId, extraJvmArgs = []) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.start(extraJvmArgs);
  return true;
}

/**
 * Stop the server.
 *
 * @param {string}  serverId
 * @param {boolean} [force=false]  true = SIGKILL immediately
 */
async function __stop_server(serverId, force = false) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.stop(force);
  return true;
}

/**
 * Restart the server.  Waits for it to fully stop before restarting.
 */
async function __restart_server(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  if (inst.running) {
    await new Promise(res => { inst.once('stop', res); inst.stop(false); });
    await new Promise(res => setTimeout(res, 1000)); // brief cooldown
  }
  inst.start();
  return true;
}

/**
 * Remove a server from the manager.  Pass deleteFiles=true to delete the folder too.
 */
async function __delete_server(serverId, deleteFiles = false) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  if (inst.running) inst.stop(true);
  if (deleteFiles) fs.rmSync(inst.dir, { recursive: true, force: true });
  _MC_SERVERS.delete(serverId);
  return true;
}

/**
 * List all managed servers.
 * @returns {object[]}  Array of { id, running, type, version, dir, players, playerCount }
 */
function __list_servers() {
  const out = [];
  for (const [id, inst] of _MC_SERVERS) {
    out.push({
      id,
      running:     inst.running,
      type:        inst.type,
      version:     inst.version,
      dir:         inst.dir,
      players:     [...inst.players],
      playerCount: inst.players.size,
      jarFile:     inst.jarFile,
      ram:         inst.opts.ram,
    });
  }
  return out;
}

/**
 * Get full details about one server.
 * Includes parsed server.properties and last 50 log lines.
 */
function __server_info(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return {
    id:          inst.id,
    running:     inst.running,
    type:        inst.type,
    version:     inst.version,
    dir:         inst.dir,
    jarFile:     inst.jarFile,
    players:     [...inst.players],
    playerCount: inst.players.size,
    ram:         inst.opts.ram,
    minRam:      inst.opts.minRam,
    properties:  _readProps(path.join(inst.dir, 'server.properties')),
    recentLog:   inst.log.slice(-50),
  };
}

/**
 * Check if a server is currently running.
 */
function __is_running(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return inst.running;
}

// ─────────────────────────────────────────────────────────────────────────────
//  VERSION MANAGEMENT
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get available Minecraft versions.
 * @param {'release'|'snapshot'|'all'} type
 * @returns {{ latest: object, versions: object[] }}
 */
async function __get_versions(type = 'release') {
  const mf = await _manifest();
  const vs  = type === 'all' ? mf.versions : mf.versions.filter(v => v.type === type);
  return {
    latest:   mf.latest,
    versions: vs.map(v => ({ id: v.id, type: v.type, releaseTime: v.releaseTime })),
  };
}

/** @returns {string}  Latest stable release version ID, e.g. '1.21.4' */
async function __get_latest_version() {
  const mf = await _manifest();
  return mf.latest.release;
}

/** @returns {string}  Latest snapshot version ID */
async function __get_latest_snapshot() {
  const mf = await _manifest();
  return mf.latest.snapshot;
}

// ─────────────────────────────────────────────────────────────────────────────
//  MOD LOADER INSTALLATION
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Install Fabric on a server.
 * Downloads Fabric's self-contained server launcher JAR — no separate installer needed.
 *
 * @param {string} serverId
 * @param {string} [mcVersion]     Defaults to server's current version
 * @param {string} [loaderVersion] Defaults to latest stable
 * @returns {{ loaderVersion, installerVersion, mcVersion }}
 */
async function __install_fabric(serverId, mcVersion, loaderVersion) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const mc       = await _resolveVersion(mcVersion || inst.version);
  const loaders  = JSON.parse(await _fetch(`${FABRIC_META}/v2/versions/loader/${mc}`));
  if (!loaders.length) throw new Error(`[mcserver] No Fabric loader found for MC ${mc}`);
  const lv       = loaderVersion || loaders[0].loader.version;
  const installs = JSON.parse(await _fetch(`${FABRIC_META}/v2/versions/installer`));
  const iv       = installs[0].version;

  const dest = path.join(inst.dir, 'fabric-server.jar');
  await _download(`${FABRIC_META}/v2/versions/loader/${mc}/${lv}/${iv}/server/jar`, dest);

  inst.type    = 'fabric';
  inst.jarFile = 'fabric-server.jar';
  inst.version = mc;
  fs.mkdirSync(path.join(inst.dir, 'mods'), { recursive: true });
  return { loaderVersion: lv, installerVersion: iv, mcVersion: mc };
}

/**
 * Install NeoForge on a server.
 * Downloads the NeoForge installer and runs it in --installServer mode.
 *
 * @param {string} serverId
 * @param {string} [mcVersion]       Defaults to server's current version
 * @param {string} [neoforgeVersion] Defaults to latest compatible
 * @returns {{ neoforgeVersion, mcVersion }}
 */
async function __install_neoforge(serverId, mcVersion, neoforgeVersion) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const mc       = await _resolveVersion(mcVersion || inst.version);
  // NeoForge versions are named after the MC minor+patch, e.g. 21.4.x for 1.21.4
  const nfBase   = mc.replace(/^1\./, '');
  const metaUrl  = `${NEOFORGE_MAVEN}/api/maven/versions/releases/net/neoforged/neoforge`;
  const meta     = JSON.parse(await _fetch(metaUrl));
  const compat   = (meta.versions || []).filter(v => v.startsWith(nfBase)).sort().reverse();
  if (!compat.length) throw new Error(`[mcserver] No NeoForge release for MC ${mc}`);
  const nfv      = neoforgeVersion || compat[0];

  const installerUrl  = `${NEOFORGE_MAVEN}/releases/net/neoforged/neoforge/${nfv}/neoforge-${nfv}-installer.jar`;
  const installerDest = path.join(inst.dir, `neoforge-${nfv}-installer.jar`);
  await _download(installerUrl, installerDest);

  await new Promise((resolve, reject) => {
    const proc = childProcess.spawn('java', ['-jar', installerDest, '--installServer'], {
      cwd:   inst.dir,
      stdio: 'inherit',
    });
    proc.on('close', code => code === 0 ? resolve() : reject(new Error(`NeoForge installer exited ${code}`)));
  });

  inst.type    = 'neoforge';
  inst.version = mc;
  // NeoForge uses a run script; find it
  const runSh  = path.join(inst.dir, 'run.sh');
  if (fs.existsSync(runSh)) {
    // Wrap the run script so ServerInstance can still use java -jar pattern
    // by symlinking / writing a launcher shim JAR path isn't needed —
    // NeoForge 1.17+ writes a unix_args.txt; we keep jarFile for the user to override
    inst.jarFile = `neoforge-${nfv}-shim.jar`;
    // Write a tiny wrapper noting the user should use the run script for full NeoForge
    fs.writeFileSync(path.join(inst.dir, '_NEOFORGE_README.txt'),
      `NeoForge installed.\nTo start: sh run.sh\nOr use __start_server which will pick up the run script automatically.\n`);
  }
  fs.mkdirSync(path.join(inst.dir, 'mods'), { recursive: true });
  return { neoforgeVersion: nfv, mcVersion: mc };
}

/**
 * Install PaperMC on a server.
 * PaperMC = high-performance Bukkit/Spigot fork with plugin support.
 *
 * @param {string} serverId
 * @param {string} [mcVersion]  Defaults to server's current version
 * @returns {{ build, mcVersion }}
 */
async function __install_paper(serverId, mcVersion) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const mc     = await _resolveVersion(mcVersion || inst.version);
  const builds = JSON.parse(await _fetch(`${PAPER_API}/projects/paper/versions/${mc}/builds`));
  const latest = builds.builds[builds.builds.length - 1];
  const jar    = latest.downloads.application.name;
  const jarUrl = `${PAPER_API}/projects/paper/versions/${mc}/builds/${latest.build}/downloads/${jar}`;
  const dest   = path.join(inst.dir, 'paper.jar');

  await _download(jarUrl, dest);
  inst.type    = 'paper';
  inst.jarFile = 'paper.jar';
  inst.version = mc;
  fs.mkdirSync(path.join(inst.dir, 'plugins'), { recursive: true });
  return { build: latest.build, mcVersion: mc };
}

/**
 * Install Purpur on a server.
 * Purpur = Paper fork with extra configuration, more mob behaviour control.
 *
 * @param {string} serverId
 * @param {string} [mcVersion]  Defaults to server's current version
 * @returns {{ build, mcVersion }}
 */
async function __install_purpur(serverId, mcVersion) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const mc   = await _resolveVersion(mcVersion || inst.version);
  const info = JSON.parse(await _fetch(`${PURPUR_API}/purpur/${mc}`));
  const bld  = info.builds.latest;
  const dest = path.join(inst.dir, 'purpur.jar');

  await _download(`${PURPUR_API}/purpur/${mc}/${bld}/download`, dest);
  inst.type    = 'purpur';
  inst.jarFile = 'purpur.jar';
  inst.version = mc;
  fs.mkdirSync(path.join(inst.dir, 'plugins'), { recursive: true });
  return { build: bld, mcVersion: mc };
}

// ─────────────────────────────────────────────────────────────────────────────
//  MOD MANAGEMENT  (Fabric / NeoForge)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Add a mod JAR from a local file path.
 * @returns {string} destination path
 */
function __add_mod(serverId, modFilePath) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const dest = path.join(inst.dir, 'mods', path.basename(modFilePath));
  fs.mkdirSync(path.join(inst.dir, 'mods'), { recursive: true });
  fs.copyFileSync(modFilePath, dest);
  return dest;
}

/**
 * Download a mod from a URL and add it to the mods folder.
 * @param {string} serverId
 * @param {string} url
 * @param {string} [filename]  Override the saved filename
 * @returns {string} destination path
 */
async function __add_mod_from_url(serverId, url, filename) {
  const inst  = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const modsDir = path.join(inst.dir, 'mods');
  fs.mkdirSync(modsDir, { recursive: true });
  const fname = filename || path.basename(new URL(url).pathname) || `mod_${Date.now()}.jar`;
  const dest  = path.join(modsDir, fname);
  await _download(url, dest);
  return dest;
}

/**
 * Remove a mod by filename.
 */
function __remove_mod(serverId, modFilename) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const p = path.join(inst.dir, 'mods', modFilename);
  if (!fs.existsSync(p)) throw new Error(`[mcserver] Mod not found: ${modFilename}`);
  fs.unlinkSync(p);
  return true;
}

/**
 * List all mods currently in the mods folder.
 * @returns {string[]}
 */
function __list_mods(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const d = path.join(inst.dir, 'mods');
  return fs.existsSync(d) ? fs.readdirSync(d).filter(f => f.endsWith('.jar')) : [];
}

// ─────────────────────────────────────────────────────────────────────────────
//  PLUGIN MANAGEMENT  (Paper / Purpur / Spigot)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Add a plugin JAR from a local path.
 */
function __add_plugin(serverId, pluginFilePath) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const dest = path.join(inst.dir, 'plugins', path.basename(pluginFilePath));
  fs.mkdirSync(path.join(inst.dir, 'plugins'), { recursive: true });
  fs.copyFileSync(pluginFilePath, dest);
  return dest;
}

/**
 * Download a plugin from a URL and add it.
 */
async function __add_plugin_from_url(serverId, url, filename) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const pluginsDir = path.join(inst.dir, 'plugins');
  fs.mkdirSync(pluginsDir, { recursive: true });
  const fname = filename || path.basename(new URL(url).pathname) || `plugin_${Date.now()}.jar`;
  const dest  = path.join(pluginsDir, fname);
  await _download(url, dest);
  return dest;
}

/**
 * Remove a plugin by filename.
 */
function __remove_plugin(serverId, pluginFilename) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const p = path.join(inst.dir, 'plugins', pluginFilename);
  if (!fs.existsSync(p)) throw new Error(`[mcserver] Plugin not found: ${pluginFilename}`);
  fs.unlinkSync(p);
  return true;
}

/**
 * List all plugins in the plugins folder.
 * @returns {string[]}
 */
function __list_plugins(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const d = path.join(inst.dir, 'plugins');
  return fs.existsSync(d) ? fs.readdirSync(d).filter(f => f.endsWith('.jar')) : [];
}

// ─────────────────────────────────────────────────────────────────────────────
//  MODRINTH INTEGRATION  (search & one-click install)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Search Modrinth for mods, plugins, resource packs, or modpacks.
 *
 * @param {string}  query
 * @param {string}  [mcVersion]  Filter by MC version
 * @param {string}  [loader]     'fabric' | 'forge' | 'neoforge' | 'bukkit' | 'paper' etc.
 * @param {string}  [type]       'mod' | 'plugin' | 'resourcepack' | 'modpack'  (default: 'mod')
 * @param {number}  [limit]      Max results (default: 10)
 * @returns {object[]}
 */
async function __search_modrinth(query, mcVersion, loader, type = 'mod', limit = 10) {
  const facets = [];
  if (mcVersion) facets.push([`versions:${mcVersion}`]);
  if (loader)    facets.push([`categories:${loader}`]);
  facets.push([`project_type:${type}`]);

  const url = `${MODRINTH_API}/search?query=${encodeURIComponent(query)}&limit=${limit}&facets=${encodeURIComponent(JSON.stringify(facets))}`;
  const raw  = JSON.parse(await _fetch(url));
  return raw.hits.map(h => ({
    id:          h.project_id,
    slug:        h.slug,
    title:       h.title,
    description: h.description,
    downloads:   h.downloads,
    follows:     h.follows,
    versions:    h.versions,
    categories:  h.categories,
    iconUrl:     h.icon_url,
    projectType: h.project_type,
    pageUrl:     `https://modrinth.com/mod/${h.slug}`,
  }));
}

/**
 * Install a mod or plugin from Modrinth by project ID or slug.
 * Automatically picks the latest version compatible with the server's MC version.
 *
 * @param {string} serverId
 * @param {string} projectIdOrSlug  e.g. 'fabric-api' or 'P7dR8mSH'
 * @returns {{ file, version, dest }}
 */
async function __install_from_modrinth(serverId, projectIdOrSlug) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);

  const mc     = inst.version;
  const loader = inst.type === 'fabric'    ? 'fabric'   :
                 inst.type === 'neoforge'  ? 'neoforge' :
                 inst.type === 'paper'     ? 'paper'    :
                 inst.type === 'purpur'    ? 'purpur'   : null;

  let versUrl = `${MODRINTH_API}/project/${projectIdOrSlug}/version?game_versions=${encodeURIComponent(JSON.stringify([mc]))}`;
  if (loader) versUrl += `&loaders=${encodeURIComponent(JSON.stringify([loader]))}`;

  const versions = JSON.parse(await _fetch(versUrl));
  if (!versions || !versions.length)
    throw new Error(`[mcserver] No Modrinth version found for "${projectIdOrSlug}" on MC ${mc} / ${loader}`);

  const best = versions[0];
  const file = best.files.find(f => f.primary) || best.files[0];

  const isPlugin  = ['paper', 'purpur', 'bukkit', 'spigot'].includes(loader);
  const targetDir = isPlugin
    ? path.join(inst.dir, 'plugins')
    : path.join(inst.dir, 'mods');
  fs.mkdirSync(targetDir, { recursive: true });

  const dest = path.join(targetDir, file.filename);
  await _download(file.url, dest);
  return { file: file.filename, version: best.version_number, dest };
}

// ─────────────────────────────────────────────────────────────────────────────
//  SERVER PROPERTIES (individual setters + raw access)
// ─────────────────────────────────────────────────────────────────────────────

/** Set any server.properties key directly. */
function __set_property(serverId, key, value) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const f = path.join(inst.dir, 'server.properties');
  const p = _readProps(f);
  p[key]  = value;
  _writeProps(f, p);
  return true;
}

/** Read any server.properties key. */
function __get_property(serverId, key) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return _readProps(path.join(inst.dir, 'server.properties'))[key];
}

/** Read all server.properties as a plain object. */
function __get_all_properties(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return _readProps(path.join(inst.dir, 'server.properties'));
}

/** Set the MOTD. Supports § colour codes. */
function __set_motd(serverId, motd) {
  return __set_property(serverId, 'motd', motd);
}

/** Set max players. */
function __set_max_players(serverId, count) {
  return __set_property(serverId, 'max-players', count);
}

/** Set default gamemode: 'survival' | 'creative' | 'adventure' | 'spectator' */
function __set_gamemode(serverId, mode) {
  return __set_property(serverId, 'gamemode', mode);
}

/** Set difficulty: 'peaceful' | 'easy' | 'normal' | 'hard' */
function __set_difficulty(serverId, difficulty) {
  return __set_property(serverId, 'difficulty', difficulty);
}

/** Set the server port. */
function __set_port(serverId, port) {
  return __set_property(serverId, 'server-port', port);
}

/** online-mode: false = allow cracked / offline clients. */
function __set_online_mode(serverId, enabled) {
  return __set_property(serverId, 'online-mode', enabled);
}

/** Enable or disable the whitelist (also sets enforce-whitelist). */
function __set_whitelist_enabled(serverId, enabled) {
  __set_property(serverId, 'white-list',         enabled);
  __set_property(serverId, 'enforce-whitelist',  enabled);
  return true;
}

/** Set view distance (2–32). */
function __set_view_distance(serverId, distance) {
  return __set_property(serverId, 'view-distance', distance);
}

/** Enable or disable PvP. */
function __set_pvp(serverId, enabled) {
  return __set_property(serverId, 'pvp', enabled);
}

/** Set the world seed. */
function __set_seed(serverId, seed) {
  return __set_property(serverId, 'level-seed', seed);
}

/** Enable RCON with given port and password. */
function __enable_rcon(serverId, port = 25575, password = 'changeme') {
  __set_property(serverId, 'enable-rcon',   'true');
  __set_property(serverId, 'rcon.port',     port);
  __set_property(serverId, 'rcon.password', password);
  return true;
}

/** Set a resource pack URL (and optional SHA-1 hash for verification). */
function __set_resource_pack(serverId, url, sha1 = '', required = false) {
  __set_property(serverId, 'resource-pack',          url);
  __set_property(serverId, 'resource-pack-sha1',     sha1);
  __set_property(serverId, 'resource-pack-required', required);
  return true;
}

/** Set max RAM and min RAM for the JVM. */
function __set_ram(serverId, maxRam, minRam = '512M') {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.opts.ram    = maxRam;
  inst.opts.minRam = minRam;
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  IN-GAME COMMANDS
// ─────────────────────────────────────────────────────────────────────────────

/** Run any raw command on a running server via its stdin. */
function __run_command(serverId, command) {
  _MC_SERVERS.get(serverId)?.command(command) ?? (() => { throw new Error(`[mcserver] Unknown server: ${serverId}`); })();
  return true;
}

/** Broadcast a message to all players (/say). */
function __broadcast_message(serverId, message) {
  return __run_command(serverId, `say ${message}`);
}

/** Send a private message to one player (/msg). */
function __send_to_player(serverId, player, message) {
  return __run_command(serverId, `msg ${player} ${message}`);
}

/** Kick a player with an optional reason. */
function __kick_player(serverId, player, reason = 'Kicked by admin') {
  return __run_command(serverId, `kick ${player} ${reason}`);
}

/** Ban a player. */
function __ban_player(serverId, player, reason = 'Banned by admin') {
  return __run_command(serverId, `ban ${player} ${reason}`);
}

/** Unban (pardon) a player. */
function __unban_player(serverId, player) {
  return __run_command(serverId, `pardon ${player}`);
}

/** Ban an IP address. */
function __ban_ip(serverId, ip, reason = 'Banned by admin') {
  return __run_command(serverId, `ban-ip ${ip} ${reason}`);
}

/** Give a player operator status. */
function __op_player(serverId, player) {
  return __run_command(serverId, `op ${player}`);
}

/** Remove operator status from a player. */
function __deop_player(serverId, player) {
  return __run_command(serverId, `deop ${player}`);
}

/** Add a player to the whitelist. */
function __whitelist_add(serverId, player) {
  return __run_command(serverId, `whitelist add ${player}`);
}

/** Remove a player from the whitelist. */
function __whitelist_remove(serverId, player) {
  return __run_command(serverId, `whitelist remove ${player}`);
}

/** Teleport a player to another player, or to XYZ coordinates. */
function __teleport(serverId, player, targetOrX, y, z) {
  if (y != null && z != null)
    return __run_command(serverId, `tp ${player} ${targetOrX} ${y} ${z}`);
  return __run_command(serverId, `tp ${player} ${targetOrX}`);
}

/** Give items to a player. */
function __give_item(serverId, player, itemId, count = 1) {
  return __run_command(serverId, `give ${player} ${itemId} ${count}`);
}

/** Set a specific player's gamemode. */
function __set_player_gamemode(serverId, player, mode) {
  return __run_command(serverId, `gamemode ${mode} ${player}`);
}

/** Heal a player to full health. */
function __heal_player(serverId, player) {
  return __run_command(serverId, `effect give ${player} minecraft:instant_health 1 255 true`);
}

/** Save the world now (/save-all). */
function __save_world(serverId) {
  return __run_command(serverId, 'save-all');
}

/** Enable or disable auto-saving. */
function __save_toggle(serverId, enabled) {
  return __run_command(serverId, enabled ? 'save-on' : 'save-off');
}

/** Set weather: 'clear' | 'rain' | 'thunder'.  Optional duration in seconds. */
function __set_weather(serverId, weather, duration) {
  return __run_command(serverId, duration ? `weather ${weather} ${duration}` : `weather ${weather}`);
}

/** Set time: 'day' | 'night' | 'noon' | 'midnight' | <ticks>. */
function __set_time(serverId, time) {
  return __run_command(serverId, `time set ${time}`);
}

/** Set game rule (e.g. 'keepInventory' true). */
function __set_gamerule(serverId, rule, value) {
  return __run_command(serverId, `gamerule ${rule} ${value}`);
}

/** Kill all mobs of a type (e.g. 'creeper', '@e[type=zombie]'). */
function __kill_mobs(serverId, selector = '@e[type=!player]') {
  return __run_command(serverId, `kill ${selector}`);
}

/** Set the world border size in blocks. */
function __set_world_border(serverId, diameter) {
  return __run_command(serverId, `worldborder set ${diameter}`);
}

/** Execute an arbitrary function (datapack). */
function __run_function(serverId, functionPath) {
  return __run_command(serverId, `function ${functionPath}`);
}

// ─────────────────────────────────────────────────────────────────────────────
//  PLAYER INFO
// ─────────────────────────────────────────────────────────────────────────────

/** @returns {string[]}  Usernames of online players */
function __get_players(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return [...inst.players];
}

/** @returns {number} */
function __player_count(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return inst.players.size;
}

/** @returns {boolean} */
function __is_player_online(serverId, playerName) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return inst.players.has(playerName);
}

// ─────────────────────────────────────────────────────────────────────────────
//  EVENTS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Subscribe to a server event.
 * Built-in events: 'player_join'  → cb(username)
 *                  'player_leave' → cb(username)
 *                  'chat'         → cb({ player, message })
 *                  'ready'        → cb()
 *                  'stop'         → cb(exitCode)
 *                  'log'          → cb(line)
 *                  'error'        → cb(Error)
 */
function __on_event(serverId, event, callback) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.on(event, callback);
  return true;
}

/** Remove a previously registered event listener. */
function __off_event(serverId, event, callback) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.off(event, callback);
  return true;
}

/** Shorthand: called when a player joins. */
function __on_player_join(serverId, cb)  { return __on_event(serverId, 'player_join',  cb); }
/** Shorthand: called when a player leaves. */
function __on_player_leave(serverId, cb) { return __on_event(serverId, 'player_leave', cb); }
/** Shorthand: called on every chat message. */
function __on_chat(serverId, cb)         { return __on_event(serverId, 'chat',         cb); }
/** Shorthand: called once the server finishes loading. */
function __on_ready(serverId, cb)        { return __on_event(serverId, 'ready',        cb); }
/** Shorthand: called when the server process exits. */
function __on_stop(serverId, cb)         { return __on_event(serverId, 'stop',         cb); }
/** Shorthand: called on every console log line. */
function __on_log(serverId, cb)          { return __on_event(serverId, 'log',          cb); }

// ─────────────────────────────────────────────────────────────────────────────
//  WORLD BACKUP & RESTORE
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Back up the world folder to a .tar.gz archive in the server's backups/ directory.
 *
 * @param {string} serverId
 * @param {string} [backupName]  Optional filename (auto-generated from timestamp otherwise)
 * @returns {string} path to the backup archive
 */
async function __backup_world(serverId, backupName) {
  const inst  = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const world = __get_property(serverId, 'level-name') || 'world';
  const bkDir = path.join(inst.dir, 'backups');
  fs.mkdirSync(bkDir, { recursive: true });
  const fname = backupName || `world-backup-${new Date().toISOString().replace(/[:.]/g, '-')}.tar.gz`;
  const dest  = path.join(bkDir, fname);
  await new Promise((resolve, reject) => {
    const p = childProcess.spawn('tar', ['-czf', dest, '-C', inst.dir, world]);
    p.on('close', code => code === 0 ? resolve() : reject(new Error(`tar exited ${code}`)));
  });
  return dest;
}

/**
 * Restore a world from a .tar.gz backup.
 * The server must be stopped first.
 */
async function __restore_world(serverId, backupFilePath) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  if (inst.running) throw new Error('[mcserver] Stop the server before restoring a world.');
  const world = __get_property(serverId, 'level-name') || 'world';
  const wd    = path.join(inst.dir, world);
  if (fs.existsSync(wd)) fs.rmSync(wd, { recursive: true });
  await new Promise((resolve, reject) => {
    const p = childProcess.spawn('tar', ['-xzf', backupFilePath, '-C', inst.dir]);
    p.on('close', code => code === 0 ? resolve() : reject(new Error(`tar exited ${code}`)));
  });
  return true;
}

/**
 * List all backups for a server.
 * @returns {{ name, path, sizeMB, created }[]}
 */
function __list_backups(serverId) {
  const inst   = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const bkDir  = path.join(inst.dir, 'backups');
  if (!fs.existsSync(bkDir)) return [];
  return fs.readdirSync(bkDir).map(f => {
    const full = path.join(bkDir, f);
    const st   = fs.statSync(full);
    return { name: f, path: full, sizeMB: +(st.size / 1048576).toFixed(2), created: st.mtime };
  });
}

/** Delete a specific backup by filename. */
function __delete_backup(serverId, backupFilename) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const p = path.join(inst.dir, 'backups', backupFilename);
  if (!fs.existsSync(p)) throw new Error(`[mcserver] Backup not found: ${backupFilename}`);
  fs.unlinkSync(p);
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  RCON CLIENT
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Connect to any Minecraft server's RCON interface.
 * The server must have enable-rcon=true and a rcon.password set.
 *
 * @param {string} host
 * @param {number} port      RCON port (usually 25575)
 * @param {string} password  rcon.password value
 * @returns {string}  rconId
 */
async function __rcon_connect(host, port, password) {
  const id   = `rcon_${++_rconCounter}`;
  const conn = new RconConnection(host, port, password);
  await conn.connect();
  _MC_RCONS.set(id, conn);
  return id;
}

/**
 * Send a command over RCON.  Returns the server's text response.
 *
 * @param {string} rconId
 * @param {string} command
 * @returns {Promise<string>}
 */
async function __rcon_command(rconId, command) {
  const conn = _MC_RCONS.get(rconId);
  if (!conn) throw new Error(`[mcserver] Unknown RCON connection: ${rconId}`);
  return conn.command(command);
}

/** Disconnect an RCON session. */
function __rcon_disconnect(rconId) {
  const conn = _MC_RCONS.get(rconId);
  if (!conn) throw new Error(`[mcserver] Unknown RCON connection: ${rconId}`);
  conn.disconnect();
  _MC_RCONS.delete(rconId);
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  REMOTE SERVER PING  (Minecraft status protocol — works on any server)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Ping any Minecraft server and return its public status.
 * This uses the MC 1.7+ status protocol and works without any mod.
 *
 * @param {string} host
 * @param {number} [port=25565]
 * @returns {{ version, players, description, favicon }}
 */
async function __ping_server(host, port = 25565) {
  return new Promise((resolve, reject) => {
    const sock = net.createConnection({ host, port });
    let done   = false;
    let buf    = Buffer.alloc(0);

    sock.setTimeout(6000, () => { if (!done) { sock.destroy(); reject(new Error('Ping timeout')); } });
    sock.on('error', e => { if (!done) reject(e); });

    sock.on('connect', () => {
      // Build handshake packet (packet id 0x00)
      const hb       = Buffer.from(host, 'utf8');
      const body     = Buffer.alloc(7 + hb.length);
      let i          = 0;
      body[i++]      = 0x00;        // packet id
      body[i++]      = 0x00;        // protocol (-1 / 0 = any)
      body[i++]      = hb.length;   // host length (VarInt shortcut)
      hb.copy(body, i); i += hb.length;
      body.writeUInt16BE(port, i); i += 2;
      body[i]        = 0x01;        // next state: status

      // Length-prefixed packet
      const lenBuf   = Buffer.alloc(1);
      lenBuf[0]      = body.length;
      sock.write(Buffer.concat([lenBuf, body]));
      // Status request packet (0x01 0x00)
      sock.write(Buffer.from([0x01, 0x00]));
    });

    sock.on('data', (chunk) => {
      buf = Buffer.concat([buf, chunk]);
      const js = buf.indexOf('{');
      const je = buf.lastIndexOf('}');
      if (js !== -1 && je > js) {
        try {
          const json = JSON.parse(buf.slice(js, je + 1).toString());
          done = true;
          sock.destroy();
          resolve({
            version:     json.version,
            players:     json.players,
            description: json.description,
            favicon:     json.favicon ? '[base64 favicon present]' : null,
          });
        } catch (_) { /* keep buffering */ }
      }
    });
  });
}

// ─────────────────────────────────────────────────────────────────────────────
//  FILE UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

/** Write any file inside the server's directory (e.g. config files). */
function __write_server_file(serverId, relPath, content) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const full = path.join(inst.dir, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  return full;
}

/** Read any file from inside the server's directory. */
function __read_server_file(serverId, relPath) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  const full = path.join(inst.dir, relPath);
  if (!fs.existsSync(full)) throw new Error(`[mcserver] File not found: ${relPath}`);
  return fs.readFileSync(full, 'utf8');
}

/** Get the absolute path to the server directory. */
function __server_dir(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return inst.dir;
}

// ─────────────────────────────────────────────────────────────────────────────
//  LOG ACCESS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get the last N log lines for a server (each line is { time, line }).
 * @param {string} serverId
 * @param {number} [lines=100]
 * @returns {{ time: number, line: string }[]}
 */
function __get_log(serverId, lines = 100) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  return inst.log.slice(-lines);
}

/** Clear the in-memory log buffer. */
function __clear_log(serverId) {
  const inst = _MC_SERVERS.get(serverId);
  if (!inst) throw new Error(`[mcserver] Unknown server: ${serverId}`);
  inst.log = [];
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
//  SYSTEM UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Check Java availability and version.
 * @param {number} [minVersion=17]
 * @returns {{ available, version, meets }}
 */
function __check_java(minVersion = 17) {
  return _javaCheck(minVersion);
}

/**
 * Check if a port is free (true = free, false = in use).
 * @param {number} port
 * @returns {Promise<boolean>}
 */
function __check_port(port) {
  return new Promise(resolve => {
    const s = net.createServer();
    s.once('error', () => resolve(false));
    s.once('listening', () => { s.close(); resolve(true); });
    s.listen(port);
  });
}

/**
 * Get host system information.
 * @returns {{ totalMemGB, freeMemGB, cpus, platform, arch, uptimeHours }}
 */
function __system_info() {
  return {
    totalMemGB:  +(os.totalmem()  / 1073741824).toFixed(2),
    freeMemGB:   +(os.freemem()   / 1073741824).toFixed(2),
    cpus:        os.cpus().length,
    platform:    os.platform(),
    arch:        os.arch(),
    uptimeHours: +(os.uptime() / 3600).toFixed(2),
  };
}

// ══════════════════════════════════════════════════════════════════════════════
//  DSALibraries REGISTRATION  (matches server.zl loader pattern)
// ══════════════════════════════════════════════════════════════════════════════
if (typeof DSALibraries !== 'undefined') {
  DSALibraries['mcserver.zl'] = {

    description:
      'Full-featured Minecraft server management library for ZPP. ' +
      'All functions are injected globally with the __ prefix. ' +
      'Supports Vanilla, Fabric, NeoForge, PaperMC, and Purpur servers. ' +
      'Downloads any MC version automatically. ' +
      'Server: __create_server __download_server_jar __start_server __stop_server ' +
      '__restart_server __delete_server __list_servers __server_info __is_running. ' +
      'Versions: __get_versions __get_latest_version __get_latest_snapshot. ' +
      'Loaders: __install_fabric __install_neoforge __install_paper __install_purpur. ' +
      'Mods: __add_mod __add_mod_from_url __remove_mod __list_mods. ' +
      'Plugins: __add_plugin __add_plugin_from_url __remove_plugin __list_plugins. ' +
      'Modrinth: __search_modrinth __install_from_modrinth. ' +
      'Properties: __set_property __get_property __get_all_properties __set_motd ' +
      '__set_max_players __set_gamemode __set_difficulty __set_port __set_online_mode ' +
      '__set_whitelist_enabled __set_view_distance __set_pvp __set_seed __enable_rcon ' +
      '__set_resource_pack __set_ram. ' +
      'Commands: __run_command __broadcast_message __send_to_player __kick_player ' +
      '__ban_player __unban_player __ban_ip __op_player __deop_player ' +
      '__whitelist_add __whitelist_remove __teleport __give_item __set_player_gamemode ' +
      '__heal_player __save_world __save_toggle __set_weather __set_time ' +
      '__set_gamerule __kill_mobs __set_world_border __run_function. ' +
      'Players: __get_players __player_count __is_player_online. ' +
      'Events: __on_event __off_event __on_player_join __on_player_leave __on_chat ' +
      '__on_ready __on_stop __on_log. ' +
      'Backup: __backup_world __restore_world __list_backups __delete_backup. ' +
      'RCON: __rcon_connect __rcon_command __rcon_disconnect. ' +
      'Network: __ping_server __check_port. ' +
      'Files: __write_server_file __read_server_file __server_dir __get_log __clear_log. ' +
      'System: __check_java __system_info.',

    inject(G) {
      // ── Server lifecycle ────────────────────────────────
      G.__create_server         = __create_server;
      G.__download_server_jar   = __download_server_jar;
      G.__start_server          = __start_server;
      G.__stop_server           = __stop_server;
      G.__restart_server        = __restart_server;
      G.__delete_server         = __delete_server;
      G.__list_servers          = __list_servers;
      G.__server_info           = __server_info;
      G.__is_running            = __is_running;

      // ── Version management ──────────────────────────────
      G.__get_versions          = __get_versions;
      G.__get_latest_version    = __get_latest_version;
      G.__get_latest_snapshot   = __get_latest_snapshot;

      // ── Loader installation ─────────────────────────────
      G.__install_fabric        = __install_fabric;
      G.__install_neoforge      = __install_neoforge;
      G.__install_paper         = __install_paper;
      G.__install_purpur        = __install_purpur;

      // ── Mod management ──────────────────────────────────
      G.__add_mod               = __add_mod;
      G.__add_mod_from_url      = __add_mod_from_url;
      G.__remove_mod            = __remove_mod;
      G.__list_mods             = __list_mods;

      // ── Plugin management ───────────────────────────────
      G.__add_plugin            = __add_plugin;
      G.__add_plugin_from_url   = __add_plugin_from_url;
      G.__remove_plugin         = __remove_plugin;
      G.__list_plugins          = __list_plugins;

      // ── Modrinth ────────────────────────────────────────
      G.__search_modrinth       = __search_modrinth;
      G.__install_from_modrinth = __install_from_modrinth;

      // ── Server properties ───────────────────────────────
      G.__set_property          = __set_property;
      G.__get_property          = __get_property;
      G.__get_all_properties    = __get_all_properties;
      G.__set_motd              = __set_motd;
      G.__set_max_players       = __set_max_players;
      G.__set_gamemode          = __set_gamemode;
      G.__set_difficulty        = __set_difficulty;
      G.__set_port              = __set_port;
      G.__set_online_mode       = __set_online_mode;
      G.__set_whitelist_enabled = __set_whitelist_enabled;
      G.__set_view_distance     = __set_view_distance;
      G.__set_pvp               = __set_pvp;
      G.__set_seed              = __set_seed;
      G.__enable_rcon           = __enable_rcon;
      G.__set_resource_pack     = __set_resource_pack;
      G.__set_ram               = __set_ram;

      // ── In-game commands ────────────────────────────────
      G.__run_command           = __run_command;
      G.__broadcast_message     = __broadcast_message;
      G.__send_to_player        = __send_to_player;
      G.__kick_player           = __kick_player;
      G.__ban_player            = __ban_player;
      G.__unban_player          = __unban_player;
      G.__ban_ip                = __ban_ip;
      G.__op_player             = __op_player;
      G.__deop_player           = __deop_player;
      G.__whitelist_add         = __whitelist_add;
      G.__whitelist_remove      = __whitelist_remove;
      G.__teleport              = __teleport;
      G.__give_item             = __give_item;
      G.__set_player_gamemode   = __set_player_gamemode;
      G.__heal_player           = __heal_player;
      G.__save_world            = __save_world;
      G.__save_toggle           = __save_toggle;
      G.__set_weather           = __set_weather;
      G.__set_time              = __set_time;
      G.__set_gamerule          = __set_gamerule;
      G.__kill_mobs             = __kill_mobs;
      G.__set_world_border      = __set_world_border;
      G.__run_function          = __run_function;

      // ── Player info ─────────────────────────────────────
      G.__get_players           = __get_players;
      G.__player_count          = __player_count;
      G.__is_player_online      = __is_player_online;

      // ── Events ──────────────────────────────────────────
      G.__on_event              = __on_event;
      G.__off_event             = __off_event;
      G.__on_player_join        = __on_player_join;
      G.__on_player_leave       = __on_player_leave;
      G.__on_chat               = __on_chat;
      G.__on_ready              = __on_ready;
      G.__on_stop               = __on_stop;
      G.__on_log                = __on_log;

      // ── World backup ────────────────────────────────────
      G.__backup_world          = __backup_world;
      G.__restore_world         = __restore_world;
      G.__list_backups          = __list_backups;
      G.__delete_backup         = __delete_backup;

      // ── RCON ────────────────────────────────────────────
      G.__rcon_connect          = __rcon_connect;
      G.__rcon_command          = __rcon_command;
      G.__rcon_disconnect       = __rcon_disconnect;

      // ── Network ─────────────────────────────────────────
      G.__ping_server           = __ping_server;
      G.__check_port            = __check_port;

      // ── File utilities ──────────────────────────────────
      G.__write_server_file     = __write_server_file;
      G.__read_server_file      = __read_server_file;
      G.__server_dir            = __server_dir;
      G.__get_log               = __get_log;
      G.__clear_log             = __clear_log;

      // ── System ──────────────────────────────────────────
      G.__check_java            = __check_java;
      G.__system_info           = __system_info;

      // ── Register names with the ZPP runtime ─────────────
      if (typeof window !== 'undefined' && window.__ZPP__) {
        window.__ZPP__.registerBuiltins([
          '__create_server', '__download_server_jar', '__start_server',
          '__stop_server', '__restart_server', '__delete_server',
          '__list_servers', '__server_info', '__is_running',
          '__get_versions', '__get_latest_version', '__get_latest_snapshot',
          '__install_fabric', '__install_neoforge', '__install_paper', '__install_purpur',
          '__add_mod', '__add_mod_from_url', '__remove_mod', '__list_mods',
          '__add_plugin', '__add_plugin_from_url', '__remove_plugin', '__list_plugins',
          '__search_modrinth', '__install_from_modrinth',
          '__set_property', '__get_property', '__get_all_properties',
          '__set_motd', '__set_max_players', '__set_gamemode', '__set_difficulty',
          '__set_port', '__set_online_mode', '__set_whitelist_enabled',
          '__set_view_distance', '__set_pvp', '__set_seed',
          '__enable_rcon', '__set_resource_pack', '__set_ram',
          '__run_command', '__broadcast_message', '__send_to_player',
          '__kick_player', '__ban_player', '__unban_player', '__ban_ip',
          '__op_player', '__deop_player', '__whitelist_add', '__whitelist_remove',
          '__teleport', '__give_item', '__set_player_gamemode', '__heal_player',
          '__save_world', '__save_toggle', '__set_weather', '__set_time',
          '__set_gamerule', '__kill_mobs', '__set_world_border', '__run_function',
          '__get_players', '__player_count', '__is_player_online',
          '__on_event', '__off_event',
          '__on_player_join', '__on_player_leave', '__on_chat',
          '__on_ready', '__on_stop', '__on_log',
          '__backup_world', '__restore_world', '__list_backups', '__delete_backup',
          '__rcon_connect', '__rcon_command', '__rcon_disconnect',
          '__ping_server', '__check_port',
          '__write_server_file', '__read_server_file', '__server_dir',
          '__get_log', '__clear_log',
          '__check_java', '__system_info',
        ]);
      }
    },
  };
}

// ── CommonJS export (Node.js direct require) ──────────────────────────────────
if (typeof module !== 'undefined') {
  module.exports = {
    __create_server, __download_server_jar, __start_server,
    __stop_server, __restart_server, __delete_server,
    __list_servers, __server_info, __is_running,
    __get_versions, __get_latest_version, __get_latest_snapshot,
    __install_fabric, __install_neoforge, __install_paper, __install_purpur,
    __add_mod, __add_mod_from_url, __remove_mod, __list_mods,
    __add_plugin, __add_plugin_from_url, __remove_plugin, __list_plugins,
    __search_modrinth, __install_from_modrinth,
    __set_property, __get_property, __get_all_properties,
    __set_motd, __set_max_players, __set_gamemode, __set_difficulty,
    __set_port, __set_online_mode, __set_whitelist_enabled,
    __set_view_distance, __set_pvp, __set_seed,
    __enable_rcon, __set_resource_pack, __set_ram,
    __run_command, __broadcast_message, __send_to_player,
    __kick_player, __ban_player, __unban_player, __ban_ip,
    __op_player, __deop_player, __whitelist_add, __whitelist_remove,
    __teleport, __give_item, __set_player_gamemode, __heal_player,
    __save_world, __save_toggle, __set_weather, __set_time,
    __set_gamerule, __kill_mobs, __set_world_border, __run_function,
    __get_players, __player_count, __is_player_online,
    __on_event, __off_event,
    __on_player_join, __on_player_leave, __on_chat,
    __on_ready, __on_stop, __on_log,
    __backup_world, __restore_world, __list_backups, __delete_backup,
    __rcon_connect, __rcon_command, __rcon_disconnect,
    __ping_server, __check_port,
    __write_server_file, __read_server_file, __server_dir,
    __get_log, __clear_log,
    __check_java, __system_info,
  };
}